### ISSUE TITLE
ERROR: iot_tls_connect L#232  failed ! mbedtls_ssl_handshake returned -0x2700

### ISSUE THREAD

**Issue by shrinivasragolu** [aws/aws-iot-device-sdk-embedded-C#981] opened 2020-06-04 16:38 UTC
Hi All,
I have ported mbedtls, awsiotsdk-c and applications provided by AWS IOT SDK to embedded Linux platform(Renesas RZA2M board). Find the versions of libraries.

1) mbedtls  --->2.16.6
2) AWS IoT SDK ---> 3.0.1(release version)

aws-iot-config.h
===========
#define AWS_IOT_MQTT_HOST              "a2g7twmqo7hg82-ats.iot.ap-south-1.amazonaws.com" ///< Customer specific MQTT HOST. The same will be used for Thing Shadow
#define AWS_IOT_MQTT_PORT              443 ///< default port for MQTT/S
#define AWS_IOT_MQTT_CLIENT_ID         "RZA2M" ///< MQTT client ID should be unique for every device
#define AWS_IOT_MY_THING_NAME              "RZA2M" ///< Thing Name of the Shadow this device is associated with
#define AWS_IOT_ROOT_CA_FILENAME       "root-CA.crt" ///< Root CA file name
#define AWS_IOT_CERTIFICATE_FILENAME   "device.pem.crt" ///< device signed certificate file name
#define AWS_IOT_PRIVATE_KEY_FILENAME   "private.pem.key" ///< Device private key filename
// =================================================

_**Note: I have renamed downloaded certificates from AWS IoT core as above and tried with same names also **_

When I run pubsub library based application, I got below error and not able to understand what is the problem. I have used downloaded certificates as it is. I have certificates directory to /tmp for my convinience.

Log
===
Certificates Directory is
rootCA = /tmp/root-CA.crt
clientCRT = /tmp/device.pem.crt
clientKey = /tmp/private.pem.key
DEBUG:   iot_tls_connect L#130
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to a2g7twmqo7hg82-ats.iot.ap-south-1.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223

SSL state connect : 0
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228

SSL state connect : 0
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:6C:9F:CF:99:BF:8C:0A:39:E2:F0:78:8A:43:E6:96:36:5B:CA
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, CN=Amazon Root CA 1
issued  on        : 2015-05-26 00:00:00
expires on        : 2038-01-17 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
issued  on        : 2015-10-22 00:00:00
expires on        : 2025-10-19 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 08:E0:24:7A:A0:55:AD:C8:10:B1:10:4A:A9:A3:B5:B0
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.ap-south-1.amazonaws.com
issued  on        : 2019-10-29 00:00:00
expires on        : 2020-10-17 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : *.iot.ap-south-1.amazonaws.com, iot.ap-south-1.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#56 cert. version     : 3
serial number     : 08:E0:24:7A:A0:55:AD:C8:10:B1:10:4A:A9:A3:B5:B0
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.ap-south-1.amazonaws.com
issued  on        : 2019-10-29 00:00:00
expires on        : 2020-10-17 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : *.iot.ap-south-1.amazonaws.com, iot.ap-south-1.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#56 cert. version     : 3
serial number     : 08:E0:24:7A:A0:55:AD:C8:10:B1:10:4A:A9:A3:B5:B0
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.ap-south-1.amazonaws.com
issued  on        : 2019-10-29 00:00:00
expires on        : 2020-10-17 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : *.iot.ap-south-1.amazonaws.com, iot.ap-south-1.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#57 cert. version     : 3
serial number     : 08:E0:24:7A:A0:55:AD:C8:10:B1:10:4A:A9:A3:B5:B0
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.ap-south-1.amazonaws.com
issued  on        : 2019-10-29 00:00:00
expires on        : 2020-10-17 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : *.iot.ap-south-1.amazonaws.com, iot.ap-south-1.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x2700

ERROR: iot_tls_connect L#234     Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes

*******************************************************************************************************
I have tried port 443 and 8883 as well. But getting the same issue. Please help me in resolving this issue.

Thanks,
Srinivas.

**Comment by pvyawaha** [comment] 2020-06-09 00:27
Hello,

Can you please confirm if the root CA used is [AmazonRootCA1](https://www.amazontrust.com/repository/AmazonRootCA1.pem) ?

**Comment by shrinivasragolu** [comment] 2020-06-10 11:29
Yes. I have used AmazonRootCA1 on Ubuntu 18.04 setup, but it did not work. So changed to G2-RootCA1.pem, then worked on Ubuntu 18.04. So I am using the same CA certificate, but end up with tls handshake error -0X50

Detailed log for mbedtls handshake
===========================
$ ./ssl_client2 server_name=a2g7twmqo7hg82-ats.iot.ap-south-1.amazonaws.com serv
er_port=443 ca_file=/certs/G2-RootCA1.pem crt_file=/certs/4960bd2f6b-certificate
.pem.crt key_file=/certs/4960bd2f6b-private.pem.key

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the client cert. and key... ok
  . Connecting to tcp/a2g7twmqo7hg82-ats.iot.ap-south-1.amazonaws.com/443... ok
  . Setting up the SSL/TLS structure...ssl_tls.c:0081: |3| set_timer to 0 ms
 ok
  . Performing the SSL/TLS handshake...ssl_tls.c:8084: |2| => handshake
ssl_cli.c:3510: |2| client state: 0
ssl_tls.c:2755: |2| => flush output
ssl_tls.c:2767: |2| <= flush output
ssl_cli.c:3510: |2| client state: 1
ssl_tls.c:2755: |2| => flush output
ssl_tls.c:2767: |2| <= flush output
ssl_cli.c:0774: |2| => write client hello
ssl_cli.c:0811: |3| client hello, max version: [3:3]
ssl_cli.c:0703: |3| client hello, current time: 1540978569
ssl_cli.c:0821: |3| dumping 'client hello, random bytes' (32 bytes)
ssl_cli.c:0821: |3| 0000:  5b d9 77 89 cd 69 d9 19 55 3f e1 ad eb 8f ce ba  [.w..i..U?......
ssl_cli.c:0821: |3| 0010:  b3 27 6b af 3f 31 55 88 7b 97 31 70 2d e1 3f 62  .'k.?1U.{.1p-.?b
ssl_cli.c:0874: |3| client hello, session id len.: 0
ssl_cli.c:0875: |3| dumping 'client hello, session id' (0 bytes)
ssl_cli.c:0921: |3| client hello, add ciphersuite: cca8
ssl_cli.c:0921: |3| client hello, add ciphersuite: cca9
ssl_cli.c:0921: |3| client hello, add ciphersuite: ccaa
ssl_cli.c:0921: |3| client hello, add ciphersuite: c02c
ssl_cli.c:0921: |3| client hello, add ciphersuite: c030
ssl_cli.c:0921: |3| client hello, add ciphersuite: 009f
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0ad
ssl_cli.c:0921: |3| client hello, add ciphersuite: c09f
ssl_cli.c:0921: |3| client hello, add ciphersuite: c024
ssl_cli.c:0921: |3| client hello, add ciphersuite: c028
ssl_cli.c:0921: |3| client hello, add ciphersuite: 006b
ssl_cli.c:0921: |3| client hello, add ciphersuite: c00a
ssl_cli.c:0921: |3| client hello, add ciphersuite: c014
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0039
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0af
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a3
ssl_cli.c:0921: |3| client hello, add ciphersuite: c087
ssl_cli.c:0921: |3| client hello, add ciphersuite: c08b
ssl_cli.c:0921: |3| client hello, add ciphersuite: c07d
ssl_cli.c:0921: |3| client hello, add ciphersuite: c073
ssl_cli.c:0921: |3| client hello, add ciphersuite: c077
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00c4
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0088
ssl_cli.c:0921: |3| client hello, add ciphersuite: c02b
ssl_cli.c:0921: |3| client hello, add ciphersuite: c02f
ssl_cli.c:0921: |3| client hello, add ciphersuite: 009e
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0ac
ssl_cli.c:0921: |3| client hello, add ciphersuite: c09e
ssl_cli.c:0921: |3| client hello, add ciphersuite: c023
ssl_cli.c:0921: |3| client hello, add ciphersuite: c027
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0067
ssl_cli.c:0921: |3| client hello, add ciphersuite: c009
ssl_cli.c:0921: |3| client hello, add ciphersuite: c013
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0033
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0ae
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a2
ssl_cli.c:0921: |3| client hello, add ciphersuite: c086
ssl_cli.c:0921: |3| client hello, add ciphersuite: c08a
ssl_cli.c:0921: |3| client hello, add ciphersuite: c07c
ssl_cli.c:0921: |3| client hello, add ciphersuite: c072
ssl_cli.c:0921: |3| client hello, add ciphersuite: c076
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00be
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0045
ssl_cli.c:0921: |3| client hello, add ciphersuite: ccac
ssl_cli.c:0921: |3| client hello, add ciphersuite: ccad
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00ab
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a7
ssl_cli.c:0921: |3| client hello, add ciphersuite: c038
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00b3
ssl_cli.c:0921: |3| client hello, add ciphersuite: c036
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0091
ssl_cli.c:0921: |3| client hello, add ciphersuite: c091
ssl_cli.c:0921: |3| client hello, add ciphersuite: c09b
ssl_cli.c:0921: |3| client hello, add ciphersuite: c097
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0ab
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00aa
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a6
ssl_cli.c:0921: |3| client hello, add ciphersuite: c037
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00b2
ssl_cli.c:0921: |3| client hello, add ciphersuite: c035
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0090
ssl_cli.c:0921: |3| client hello, add ciphersuite: c090
ssl_cli.c:0921: |3| client hello, add ciphersuite: c096
ssl_cli.c:0921: |3| client hello, add ciphersuite: c09a
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0aa
ssl_cli.c:0921: |3| client hello, add ciphersuite: 009d
ssl_cli.c:0921: |3| client hello, add ciphersuite: c09d
ssl_cli.c:0921: |3| client hello, add ciphersuite: 003d
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0035
ssl_cli.c:0921: |3| client hello, add ciphersuite: c032
ssl_cli.c:0921: |3| client hello, add ciphersuite: c02a
ssl_cli.c:0921: |3| client hello, add ciphersuite: c00f
ssl_cli.c:0921: |3| client hello, add ciphersuite: c02e
ssl_cli.c:0921: |3| client hello, add ciphersuite: c026
ssl_cli.c:0921: |3| client hello, add ciphersuite: c005
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a1
ssl_cli.c:0921: |3| client hello, add ciphersuite: c07b
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00c0
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0084
ssl_cli.c:0921: |3| client hello, add ciphersuite: c08d
ssl_cli.c:0921: |3| client hello, add ciphersuite: c079
ssl_cli.c:0921: |3| client hello, add ciphersuite: c089
ssl_cli.c:0921: |3| client hello, add ciphersuite: c075
ssl_cli.c:0921: |3| client hello, add ciphersuite: 009c
ssl_cli.c:0921: |3| client hello, add ciphersuite: c09c
ssl_cli.c:0921: |3| client hello, add ciphersuite: 003c
ssl_cli.c:0921: |3| client hello, add ciphersuite: 002f
ssl_cli.c:0921: |3| client hello, add ciphersuite: c031
ssl_cli.c:0921: |3| client hello, add ciphersuite: c029
ssl_cli.c:0921: |3| client hello, add ciphersuite: c00e
ssl_cli.c:0921: |3| client hello, add ciphersuite: c02d
ssl_cli.c:0921: |3| client hello, add ciphersuite: c025
ssl_cli.c:0921: |3| client hello, add ciphersuite: c004
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a0
ssl_cli.c:0921: |3| client hello, add ciphersuite: c07a
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00ba
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0041
ssl_cli.c:0921: |3| client hello, add ciphersuite: c08c
ssl_cli.c:0921: |3| client hello, add ciphersuite: c078
ssl_cli.c:0921: |3| client hello, add ciphersuite: c088
ssl_cli.c:0921: |3| client hello, add ciphersuite: c074
ssl_cli.c:0921: |3| client hello, add ciphersuite: ccae
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00ad
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00b7
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0095
ssl_cli.c:0921: |3| client hello, add ciphersuite: c093
ssl_cli.c:0921: |3| client hello, add ciphersuite: c099
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00ac
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00b6
ssl_cli.c:0921: |3| client hello, add ciphersuite: 0094
ssl_cli.c:0921: |3| client hello, add ciphersuite: c092
ssl_cli.c:0921: |3| client hello, add ciphersuite: c098
ssl_cli.c:0921: |3| client hello, add ciphersuite: ccab
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00a9
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a5
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00af
ssl_cli.c:0921: |3| client hello, add ciphersuite: 008d
ssl_cli.c:0921: |3| client hello, add ciphersuite: c08f
ssl_cli.c:0921: |3| client hello, add ciphersuite: c095
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a9
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00a8
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a4
ssl_cli.c:0921: |3| client hello, add ciphersuite: 00ae
ssl_cli.c:0921: |3| client hello, add ciphersuite: 008c
ssl_cli.c:0921: |3| client hello, add ciphersuite: c08e
ssl_cli.c:0921: |3| client hello, add ciphersuite: c094
ssl_cli.c:0921: |3| client hello, add ciphersuite: c0a8
ssl_cli.c:0934: |3| client hello, got 127 ciphersuites (excluding SCSVs)
ssl_cli.c:0943: |3| adding EMPTY_RENEGOTIATION_INFO_SCSV
ssl_cli.c:0992: |3| client hello, compress len.: 1
ssl_cli.c:0993: |3| client hello, compress alg.: 0
ssl_cli.c:0068: |3| client hello, adding server name extension: a2g7twmqo7hg82-ats.iot.ap-south-1.amazonaws.com
ssl_cli.c:0186: |3| client hello, adding signature_algorithms extension
ssl_cli.c:0271: |3| client hello, adding supported_elliptic_curves extension
ssl_cli.c:0336: |3| client hello, adding supported_point_formats extension
ssl_cli.c:0517: |3| client hello, adding encrypt_then_mac extension
ssl_cli.c:0551: |3| client hello, adding extended_master_secret extension
ssl_cli.c:0585: |3| client hello, adding session ticket extension
ssl_cli.c:1070: |3| client hello, total extension length: 128
ssl_tls.c:3184: |2| => write handshake message
ssl_tls.c:3343: |2| => write record
ssl_tls.c:3420: |3| output record: msgtype = 22, version = [3:1], msglen = 429
ssl_tls.c:3425: |4| dumping 'output record sent to network' (434 bytes)
ssl_tls.c:3425: |4| 0000:  16 03 01 01 ad 01 00 01 a9 03 03 5b d9 77 89 cd  ...........[.w..
ssl_tls.c:3425: |4| 0010:  69 d9 19 55 3f e1 ad eb 8f ce ba b3 27 6b af 3f  i..U?.......'k.?
ssl_tls.c:3425: |4| 0020:  31 55 88 7b 97 31 70 2d e1 3f 62 00 01 00 cc a8  1U.{.1p-.?b.....
ssl_tls.c:3425: |4| 0030:  cc a9 cc aa c0 2c c0 30 00 9f c0 ad c0 9f c0 24  .....,.0.......$
ssl_tls.c:3425: |4| 0040:  c0 28 00 6b c0 0a c0 14 00 39 c0 af c0 a3 c0 87  .(.k.....9......
ssl_tls.c:3425: |4| 0050:  c0 8b c0 7d c0 73 c0 77 00 c4 00 88 c0 2b c0 2f  ...}.s.w.....+./
ssl_tls.c:3425: |4| 0060:  00 9e c0 ac c0 9e c0 23 c0 27 00 67 c0 09 c0 13  .......#.'.g....
ssl_tls.c:3425: |4| 0070:  00 33 c0 ae c0 a2 c0 86 c0 8a c0 7c c0 72 c0 76  .3.........|.r.v
ssl_tls.c:3425: |4| 0080:  00 be 00 45 cc ac cc ad 00 ab c0 a7 c0 38 00 b3  ...E.........8..
ssl_tls.c:3425: |4| 0090:  c0 36 00 91 c0 91 c0 9b c0 97 c0 ab 00 aa c0 a6  .6..............
ssl_tls.c:3425: |4| 00a0:  c0 37 00 b2 c0 35 00 90 c0 90 c0 96 c0 9a c0 aa  .7...5..........
ssl_tls.c:3425: |4| 00b0:  00 9d c0 9d 00 3d 00 35 c0 32 c0 2a c0 0f c0 2e  .....=.5.2.*....
ssl_tls.c:3425: |4| 00c0:  c0 26 c0 05 c0 a1 c0 7b 00 c0 00 84 c0 8d c0 79  .&.....{.......y
ssl_tls.c:3425: |4| 00d0:  c0 89 c0 75 00 9c c0 9c 00 3c 00 2f c0 31 c0 29  ...u.....<./.1.)
ssl_tls.c:3425: |4| 00e0:  c0 0e c0 2d c0 25 c0 04 c0 a0 c0 7a 00 ba 00 41  ...-.%.....z...A
ssl_tls.c:3425: |4| 00f0:  c0 8c c0 78 c0 88 c0 74 cc ae 00 ad 00 b7 00 95  ...x...t........
ssl_tls.c:3425: |4| 0100:  c0 93 c0 99 00 ac 00 b6 00 94 c0 92 c0 98 cc ab  ................
ssl_tls.c:3425: |4| 0110:  00 a9 c0 a5 00 af 00 8d c0 8f c0 95 c0 a9 00 a8  ................
ssl_tls.c:3425: |4| 0120:  c0 a4 00 ae 00 8c c0 8e c0 94 c0 a8 00 ff 01 00  ................
ssl_tls.c:3425: |4| 0130:  00 80 00 00 00 34 00 32 00 00 2f 61 32 67 37 74  .....4.2../a2g7t
ssl_tls.c:3425: |4| 0140:  77 6d 71 6f 37 68 67 38 32 2d 61 74 73 2e 69 6f  wmqo7hg82-ats.io
ssl_tls.c:3425: |4| 0150:  74 2e 61 70 2d 73 6f 75 74 68 2d 31 2e 61 6d 61  t.ap-south-1.ama
ssl_tls.c:3425: |4| 0160:  7a 6f 6e 61 77 73 2e 63 6f 6d 00 0d 00 16 00 14  zonaws.com......
ssl_tls.c:3425: |4| 0170:  06 03 06 01 05 03 05 01 04 03 04 01 03 03 03 01  ................
ssl_tls.c:3425: |4| 0180:  02 03 02 01 00 0a 00 18 00 16 00 19 00 1c 00 18  ................
ssl_tls.c:3425: |4| 0190:  00 1b 00 17 00 16 00 1a 00 15 00 14 00 13 00 12  ................
ssl_tls.c:3425: |4| 01a0:  00 0b 00 02 01 00 00 16 00 00 00 17 00 00 00 23  ...............#
ssl_tls.c:3425: |4| 01b0:  00 00                                            ..
ssl_tls.c:2755: |2| => flush output
ssl_tls.c:2773: |2| message length: 434, out_left: 434
ssl_tls.c:2779: |2| ssl->f_send() returned 434 (-0xfffffe4e)
ssl_tls.c:2807: |2| <= flush output
ssl_tls.c:3476: |2| <= write record
ssl_tls.c:3320: |2| <= write handshake message
ssl_cli.c:1106: |2| <= write client hello
ssl_cli.c:3510: |2| client state: 2
ssl_tls.c:2755: |2| => flush output
ssl_tls.c:2767: |2| <= flush output
ssl_cli.c:1499: |2| => parse server hello
ssl_tls.c:4311: |2| => read record
ssl_tls.c:2536: |2| => fetch input
ssl_tls.c:2696: |2| in_left: 0, nb_want: 5
ssl_tls.c:2720: |2| in_left: 0, nb_want: 5
ssl_tls.c:2722: |2| ssl->f_recv(_timeout)() returned -80 (-0x0050)
ssl_tls.c:4973: |1| mbedtls_ssl_fetch_input() returned -80 (-0x0050)
ssl_tls.c:4344: |1| ssl_get_next_record() returned -80 (-0x0050)
ssl_cli.c:1506: |1| mbedtls_ssl_read_record() returned -80 (-0x0050)
ssl_tls.c:8094: |2| <= handshake
 failed
  ! mbedtls_ssl_handshake returned -0x50

Last error was: -0x50 - NET - Connection was reset by peer

ssl_tls.c:8934: |2| => free
ssl_tls.c:8999: |2| <= free

Could you please help me in resolving this connectivity isssue of mbedtls while handshake?

Thanks ,
Srinivas.

**Comment by dachalco** [comment] 2020-06-11 21:46
Duplicate of #976

**Comment by dachalco** [comment] 2020-06-11 21:50
Hello,

I noticed this was where #976 left off. As Issue #976 is still open and has more correspondence with more context, I've marked this as a duplicate and ask that we please continue there.

**Closed by dachalco** 2020-06-11 21:50 UTC
