### ISSUE TITLE
aws-iot will fail to work after a period of time

### ISSUE THREAD

**Issue by laoyouji007** [aws/aws-iot-device-sdk-embedded-C#852] opened 2020-04-03 02:03 UTC
Hello, 

After running for about half an hour, AWS IOT suddenly can't receive the data. After another 10 minutes, the following error log information will be output. Then the program will be reconnected and all functions will be restored. Why does AWS IOT fail to work after a period of time? Is it due to the network? How to avoid this problem?

Thanks !

**Output log info:**
WARN:  disconnectCallbackHandler L#558 MQTT Disconnect
Auto Reconnect is enabled, Reconnecting attempt will start now
Subscribing topic: Puppod/LambdaToDispenser/6023A4A7B410 ...
ERROR: coa_iot_init_subscribing L#1007 Error subscribing : -13

AWS IoT SDK Version 3.0.1-

DEBUG:   aws_iot_proc L#1063 rootCA /media/certs/rootCA.crt
DEBUG:   aws_iot_proc L#1064 clientCRT /media/certs/cert.pem
DEBUG:   aws_iot_proc L#1065 clientKey /media/certs/privkey.pem
iniparser: cannot open /mnt/config/kinesis_conf.ini
cannot parse file: /mnt/config/kinesis_conf.ini
Connecting...
DEBUG:   iot_tls_connect L#130
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to a32fz4wpcfmflt-ats.iot.us-east-2.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223

SSL state connect : 0
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228

SSL state connect : 0
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:6C:9F:CF:99:BF:8C:0A:39:E2:F0:78:8A:43:E6:96:36:5B:CA
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, CN=Amazon Root CA 1
issued  on        : 2015-05-26 00:00:00
expires on        : 2038-01-17 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
issued  on        : 2015-10-22 00:00:00
expires on        : 2025-10-19 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 04:B1:F9:DF:C2:BD:23:88:18:A5:2C:BE:73:31:5D:DD
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.us-east-2.amazonaws.com
issued  on        : 2020-02-17 00:00:00
expires on        : 2021-01-28 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : *.iot.us-east-2.amazonaws.com, iot.us-east-2.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   iot_tls_connect L#246  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256 ]

DEBUG:   iot_tls_connect L#248     [ Record expansion is 29 ]

DEBUG:   iot_tls_connect L#253   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#262  ok

DEBUG:   iot_tls_connect L#272   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#274       cert. version     : 3
      serial number     : 04:B1:F9:DF:C2:BD:23:88:18:A5:2C:BE:73:31:5D:DD
      issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
      subject name      : CN=*.iot.us-east-2.amazonaws.com
      issued  on        : 2020-02-17 00:00:00
      expires on        : 2021-01-28 12:00:00
      signed using      : RSA with SHA-256
      RSA key size      : 2048 bits
      basic constraints : CA=false
      subject alt name  : *.iot.us-east-2.amazonaws.com, iot.us-east-2.amazonaws.com
      key usage         : Digital Signature, Key Encipherment
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

**Comment by laoyouji007** [comment] 2020-04-03 02:12
Is there any way for AWS IOT to enable more log output, such as monitoring the heartbeat log of AWS IOT, or is there any way for the server background to view the monitoring?

**Comment by dan4thewin** [comment] 2020-04-06 18:33
@laoyouji007 , are you specifying a keep alive interval when connecting?  The broker could be disconnecting due to inactivity.  A packet capture would be helpful to diagnose this issue.  Have you tried using wireshark?

**Comment by laoyouji007** [comment] 2020-04-08 12:32
@dan4thewin 
Hello, what do you mean of `specifying a keep alive interval when connecting` ? I'm trying to use wireshark to capture packet.

**Comment by dan4thewin** [comment] 2020-04-08 17:56
There's a parameter in the connect structure to specify a keep alive interval.  https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_mqtt_client.h#L139

Here's a description from the spec: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349238

and here is a nice explanation: https://www.hivemq.com/blog/mqtt-essentials-part-10-alive-client-take-over/

**Comment by laoyouji007** [comment] 2020-04-09 06:01
@dan4thewin 
`	connectParams.keepAliveIntervalInSec = 600;
	connectParams.isCleanSession = true;
	connectParams.MQTTVersion = MQTT_3_1_1;
	connectParams.pClientID = AWS_IOT_MQTT_CLIENT_ID;
	connectParams.clientIDLen = (uint16_t) strlen(AWS_IOT_MQTT_CLIENT_ID);
	connectParams.isWillMsgPresent = false;
......
    rc = aws_iot_mqtt_connect(&aws_iot_client, &connectParams);`

I use the param of demo from aws_iot, and setting "keepAliveIntervalInSec = 600", should I make this value larger?

**Comment by dcgaws** [comment] 2020-04-13 14:58
Hello @laoyouji007 here is a previous thread about MQTT disconnects on AWS IoT that you might find helpful for background information https://forums.aws.amazon.com/thread.jspa?threadID=314646. 

In the meantime, which version/commit of our Embedded C SDK code are you using?

**Comment by laoyouji007** [comment] 2020-04-14 05:46
Hi, Finally, I found that because the topic of the function aws_iot_mqtt_subscribe(client, topic, topic_len ...) is not of static type, the topic is recycled after the program runs for a period of time. When the data sent by the server is received, it cannot be processed. After coming back several times, AWS IOT will disconnect.

Thanks all of you guys !

**Comment by yuhui-zheng** [comment] 2020-04-22 18:49
Some thoughts...
- (Not sure if you are getting the same error code.) Error code definitions could be found here. https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_error.h#L40.

The cause of disconnection may be "complicated". (I hesitate to respond in the affirmative regarding to any fixed configuration for network/MQTT settings. May have long RTT, may have heavy loaded router, may drop packet...) As @dan4thewin commented above, if could show in Wireshark that network packets all sent/arrived as intended, we could focus more on debugging device software.

**Comment by aggarg** [comment] 2020-04-27 00:27
In addition to the suggestions above, a specific issue related to the delayed ping responses, which resulted in disconnect, was fixed in this PR: https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/853

Are you using the latest code from master branch?

Thanks.

**Comment by yanjos-dev** [comment] 2020-08-12 22:34
@laoyouji007 This topic has become inactive so I'm going to close the issue. Please reopen this topic if you have any questions or if you would like any further assistance.

**Closed by yanjos-dev** 2020-08-12 22:34 UTC
