### ISSUE TITLE
How to receive complete json object in delta callback function

### ISSUE THREAD

**Issue by nikitanerkar** [aws/aws-iot-device-sdk-embedded-C#15] opened 2016-04-18 06:39 UTC
The callback function registered for aws_iot_shadow_register_delta obj, returns partial json string. In my use-case, the application is publishing and subscribed to the same thing shadow. The device has both local and remote control, due to which in some of the use-cases, delta callback function gets invoked with stale information. For example, device publishes it's state as _false_ initially, and desired state is set to _true_ using thing shadow, then the callback function gets invoked and device state is updated and published as _true_. After that, if device state is set to _false_ using local control button, and this state is published, then the callback function gets invoked again, as there is difference in desired state and reported state. This time changing device state is not desirable as the request is already processed and this requires metadata/time-stamp to skip this stale information. But as the callback function returns partial json string, parsing of the json object is becoming difficult. Is there any other way to access complete string received from the thing shadow?

**Comment by gkwicker** [comment] 2016-04-19 00:56
Hi @nikitanerkar.  One option to simplify your processing might be to save the local state of the button, and when you receive the delta containing a new value check to see if there is any difference between the desired state from the delta message and your known local state.  If there is no difference, you can safely ignore the updated state in the delta message.  Let us know if that helps, and thanks for using AWS IoT.

**Comment by nikitanerkar** [comment] 2016-04-19 06:54
Thanks for the quick reply @gkwicker. The problem I am facing is, I can't access the entire json_string in the delta callback function.
As per my understanding delta gets invoked only when there is difference in desired state and reported state. And as I am reporting the device state every-time it changes, either by local or remote entity, I am facing the issue in following scenario,
On bootup, device reports it's state as _false_. On thing shadow: {"reported": _false_}
From thing shadow, desired state is set to _true_, thing shadow gets updated as {"reported": _false_, "desired": _true_},
due to which, registered delta callback gets invoked with information,  _true},"metadata":{"state":{"timestamp":1460635549}}}_
The device state is set to _true_ and state is published. On thing shadow, {"reported": _true_, "desired": _true_}.
Till this point everything is working as per expectation.
Now, if device state is changed locally to _false_ using push-button, device publishes it's state as _false_ and thing shadow gets updated as, {"reported": _false_, "desired": _true_}.
And as there is a difference in reported and desired state, delta callback function gets invoked with pjson_string holding data, _true},"metadata":{"state":{"timestamp":1460635549}}}_
This information is already processed and needs to be ignored. Currently I am parsing this string and storing time-stamp value. If new time-stamp value is same as old time-stamp value then ignore the data.
But as I mentioned, this parsing is bit tricky due to partial json object received at the callback function, so is there any way to obtain the entire json string.

**Comment by gkwicker** [comment] 2016-04-20 21:40
Hi @nikitanerkar,

If you set the `jsonStruct_t` `pKey` field to `"state"` in the call to `aws_iot_shadow_register_delta()`, you will receive a pointer to the state data in the delta callback.  Then you'd be able to compare the values and see if they differ from your local state.  You can read about this approach in [the API documentation](http://aws-iot-device-sdk-embedded-c-docs.s3-website-us-east-1.amazonaws.com/aws__iot__shadow__interface_8h.html#a2018994362d1ecc99af2151227d5bb41) and see an example of this in the code for the [shadow_console_echo.c example application.](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/sample_apps/shadow_sample_console_echo/shadow_console_echo.c#L148).  Let us know if that helps, and thanks for using AWS IoT.

**Comment by ravichandhraRean** [comment] 2018-09-07 08:51
Hi @nikitanerkar  @gkwicker  @chaurah 

now we also getting the same issue but now we are not able to resolve this by using metadata - timestamp(because both the times the timestamp is different).

can you reopen this issue please

we want operate a device lock both remotely and manually.

1. device is locked initially and at the time of connecting to IoT it sets it's shadow like this { "reported" : { "LOCK": "locked" } }

2. after someone remotely sets shadow desired to unlocked like this { "desired" : { "LOCK" : "unlock" } } so the shadow now will be like this { "desired" : { "LOCK" : "unlock" } , "reported" : { "LOCK": "locked" }, "delta" : { "LOCK" : "unlock" } }

3. device received the delta message and unlocked and reported back like this { "reported" : { "LOCK" : "unlock" } } so the shadow now will be like this { "desired" : { "LOCK" : "unlock" } , "reported" : { "LOCK": "unlock" }}

Till this point everything working fine, 

4. but now someone manually locked the device so device reported it's current state to shadow like this
like this { "reported" : { "LOCK" : "locked" } } so here the problem comes now because the **AWS IoT NOT CLEARING THE DESIRED SECTION AFTER GETTING REPORTED**  the shadow now will be like this 
 { "desired" : { "LOCK" : "unlock" } , "reported" : { "LOCK": "locked" }, "delta" : { "LOCK" : "unlock" } } 

and immediately getting callback to device with delta message (which is not required / previously desired).

so we are not able to solve this and **AWS IoT NOT SUPPORTING BOTH REMOTE AND MANUAL OPERATION OF DEVICE(this is one use-case there will be many use-cases where both required)**

thank you.

Regards,
Ravichandhra Palla
ravichandhra.palla@reancloud.com 
REAN Cloud

**Comment by lt72** [comment] 2018-09-07 16:13
Duplicate of #229.

**Closed by lt72** 2018-09-07 16:13 UTC
Labels: area-shadow, bug, tenet-quality
