### ISSUE TITLE
Question on subscriptions + duplicates

### ISSUE THREAD

**Issue by F1nny** [aws/aws-iot-device-sdk-embedded-C#185] opened 2018-05-24 16:36 UTC
Hey all,
We have a single client ID/device that is dynamic in what topics it subscribes, we rewrote our module with the latest SDK (as it was couple months ago) since has been a while and did a major overhaul - in cases of say a network change or simply providing new wifi credentials (even same ones) what ends up happening is we reconnect and also subscribe again to the same topics to ensure we're subscribed, problem is we end up with duplicate messages coming down off one publish because of it. When looking around it appeared it shouldn't even allow this/subscribing to same topic over and over on same client ID - is that right? We're wondering if may need to try disabling auto reconnect and handle ourselves, remove our handling leaving the auto reconnect, or maybe try changing the subscriptions after state changes to resubscribes since it appears just a matter of us doing the work and the IoT SDK doing the same in these cases resulting in duplicate subscriptions. Any ideas? I assume no way to prevent this cloud side at all as IoT doesn't have many options, but find it strange it's allowing duplicate subscriptions from same client ID when that doesn't appear to be the case on the other versions of the SDK (cpp for example)?

Last question is, is there a way to determine what topics are subscribed at any given time? Going through the docs didn't see anything but haven't went down into the SDK yet, thanks all!

Also subscribing with QoS0*

**Comment by gordonwang0** [comment] 2018-05-24 20:41
Hi @F1nny,

The duplicate publish messages is actually expected behavior -- it allows users to register multiple callback functions for the same topic.  In your case, since you have the same callback registered for each topic, you will see duplicate invocations of your callback function.

**Auto-reconnect will handle re-subscribing to topics for you, so your application should not make any MQTT subscription calls upon reconnecting**.  If you disable auto-reconnect, you should call `aws_iot_mqtt_resubscribe` **once** to re-subscribe to all previously subscribed topics.  Calling `aws_iot_mqtt_resubscribe` instead of `aws_iot_mqtt_subscribe` will avoid the duplicate callback invocations.

There's no API function to check which topics currently have active subscriptions.  However, you can search `client.clientData.messageHandlers` to see which topics _should_ have an active subscription.  Something like the following:
```c
/* Assume client is initialized and connected. */
AWS_IoT_Client client;
const char* topic;
int i;

/* After a successful call to aws_iot_mqtt_resubscribe, all the topics in
 * client.clientData.messageHandlers should have active subscriptions. */
assert( aws_iot_mqtt_resubscribe( &client ) == SUCCESS );

/* AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS should be defined in your aws_iot_config.h. */
for( i = 0; i < AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS; i++ )
{
    topic = client.clientData.messageHandlers[ i ].topicName;
    if( topic != NULL )
    {
        printf( "There should be an active subscription to topic: %s.\n", topic );
    }
}
```

**Comment by gordonwang0** [comment] 2018-05-31 17:35
Hi @F1nny,

Please let me know if you need any more help on this.  Closing issue.

**Closed by gordonwang0** 2018-05-31 17:35 UTC
Labels: area-mqtt, question

**Comment by F1nny** [comment] 2018-06-01 01:14
Thanks Gordon sorry forgot to close! That was what was looking for thank you for the detailed information :)
