### ISSUE TITLE
aws_iot_shadow_register_delta is never called

### ISSUE THREAD

**Issue by fmonsalvo** [aws/aws-iot-device-sdk-embedded-C#253] opened 2018-12-27 17:25 UTC
Hello,
I have been trying to run the shadow sample console echo that comes with the SDK.
I'm facing an issue similar to the one described in #132, but I can't solve it.
I tried also the sample shadow code and it updates the shadow document, but it does not call the callback when I change the delta in the IoT console.
I'm not sure what can I be doing wrong.
I checked the certificates and they seem to be alright (The shadow update part from the device works).

**Comment by fmonsalvo** [comment] 2019-01-02 14:52
I'm attaching my configuration, maybe it can help:
```// Get from console
// =================================================
#define AWS_IOT_MQTT_HOST              "****-ats.iot.us-east-1.amazonaws.com" ///< Customer specific MQTT HOST. The same will be used for Thing Shadow
#define AWS_IOT_MQTT_PORT              443 ///< default port for MQTT/S
#define AWS_IOT_MQTT_CLIENT_ID         "finger_sta_catalina_1" ///< MQTT client ID should be unique for every device
#define AWS_IOT_MY_THING_NAME 		   "finger_client_1" ///< Thing Name of the Shadow this device is associated with
#define AWS_IOT_ROOT_CA_FILENAME       "root.pem" ///< Root CA file name
#define AWS_IOT_CERTIFICATE_FILENAME   "cert.pem.crt" ///< device signed certificate file name
#define AWS_IOT_PRIVATE_KEY_FILENAME   "privkey.pem" ///< Device private key filename
// =================================================
```

And this is the code managing the Delta:

```
        char status[MAX_LENGTH_OF_UPDATE_JSON_BUFFER];
        jsonStruct_t statusActuator;
        snprintf(status, sizeof(status), "%s", "IDLE");
	statusActuator.cb = statusActuate_Callback;
	statusActuator.pData = &status;
	statusActuator.dataLength = sizeof(status);
	statusActuator.pKey = "status";
	statusActuator.type = SHADOW_JSON_STRING;
```

**Comment by ravibhagavandas** [comment] 2019-01-02 19:16
Hi fmonsalvo@,

One of the reasons for delta callback to be not triggered is, if the incoming shadow size is greater than the maximum RX buffer size defined in configuration header file.
Could you check if the RX buffer size defined in configuration [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/64ab0465ec91646b3c369f574a5c97b05f595c59/samples/linux/shadow_sample_console_echo/aws_iot_config.h#L37) is adequate ?

Additional things to check for:
1. Is `char status[MAX_LENGTH_OF_UPDATE_JSON_BUFFER];` defined within  function call stack? If so you should make it global static.
2. Make sure the shadow JSON document contains the field with key as "status", so that callback is triggered.

Please let us know if the problem persists.

**Comment by fmonsalvo** [comment] 2019-01-03 12:15
Hi @ravibhagavandas ,
Thank you for your reply.
I double checked and I'm meeting both of your recommendations now. It's still not working.
One thing to note is that I'm also trying to run the shadow_sample_console_echo code in my raspberry pi, with the same results. I'm able to update the shadow document from the device, but it is not responding to any update done on the IoT console.

**Comment by lt72** [comment] 2019-01-12 22:50
@fmonsalvo: Hi, did Ravi's suggestion addressed your issue?

**Comment by lt72** [comment] 2019-02-01 22:02
Hi @fmonsalvo, I am closing this issue waiting to hear back from you. Please re-open it if you need further help. Thank you.

**Closed by lt72** 2019-02-01 22:02 UTC
Labels: area-shadow, bug, tenet-usability

**Comment by fmonsalvo** [comment] 2019-03-26 17:26
Sorry I took so long to reply but I had to attend other projects.
I did try using what Ravi said, but it did not help.
I'm working again on this project, so I'll let you know if I was able to fix this.
Thank you.

**Comment by innomatica** [comment] 2019-06-25 22:21
I too have the same issue. The sample code in

`aws-iot-device-sdk-embedded-C/samples/linux/shadow_sample/`

does not trigger the callback `windowActuate_Callback` when 
```
{
  "desired": {
    "windowOpen": true
  },
  "reported": {
    "temperature": 29,
    "windowOpen": false
  }
}
```
is entered using IoT Core console. All I have changed from the sample code is to provide credentials and endpoint and so on. Other features are working fine but the delta callback.

**Comment by innomatica** [comment] 2019-06-26 12:59
I figured out the cause. It was the length of my thing name, which is longer than the maximum length defined in the `aws_iot_config.h`. After increasing the value of
```
MAX_SIZE_OF_THING_NAME
```
it works as expected. I figure the default value 20 may not be enough in some cases.
