### ISSUE TITLE
SSL handshake fail when using new endpoint with '-ats' or '.ats'

### ISSUE THREAD

**Issue by tidyjiang8** [aws/aws-iot-device-sdk-embedded-C#248] opened 2018-12-10 03:12 UTC
Hi,
Our embedded device worked well, but when I try to use the new endpoint with '-ats' or '.ats', it reports `SSL_CONNECTION_ERROR`. I want to know whether you can reproduce this issue and do you have any plan to fix it if it does exist?

By the way, it's very interesting that our iOS device works well with new endpoint while doesn't work with old endpoint(without '-ats' or '.ats'). See https://github.com/aws-amplify/aws-sdk-ios/issues/1138#issuecomment-445278023

Thx!

**Comment by gordonwang0** [comment] 2018-12-10 18:02
Hi @tidyjiang8,

You must use one of the [ATS root certificates](https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html#server-authentication) when connecting to an `-ats` endpoint.  Have you switched your root certificate to one of the "Amazon Root CAs" (and not the Verisign one)?

**Comment by tidyjiang8** [comment] 2018-12-12 02:17
@gordonwang0, It works with ATS root certificate, Thanks!

**Comment by tidyjiang8** [comment] 2018-12-12 07:00
Hi @gordonwang0, 

I still have problem.

On linux platform, it does work when I use root CA "Amazon Trust Services".
But on freeRTOS platform, it still returns `SSL_CONNECTION_ERROR` when I switch to "Amazon Trust Services". And when I switch back to "VeriSign", it works again.

I does not have any idea how to debug this issue. Could you help to reproduce it on freeRTOS platform?

Attach my initialise code below:
```
#define AWS_IOT_MQTT_PORT              8883
#define AWS_IOT_ROOT_CA_ATS                                               \
"-----BEGIN CERTIFICATE-----\r\n"                                         \
"MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\r\n"    \
"ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\r\n"    \
"b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\r\n"    \
"MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\r\n"    \
"b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\r\n"    \
"ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\r\n"    \
"9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\r\n"    \
"IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\r\n"    \
"VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\r\n"    \
"93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\r\n"    \
"jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\r\n"    \
"AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\r\n"    \
"A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\r\n"    \
"U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\r\n"    \
"N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\r\n"    \
"o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\r\n"    \
"5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\r\n"    \
"rqXRfboQnoZsG4q5WTP468SQvvG5\r\n"                                        \
"-----END CERTIFICATE-----"

 IoT_Client_Init_Params ip = iotClientInitParamsDefault;
 ip.enableAutoReconnect = true;
 ip.pHostURL = end_point;
 ip.port = AWS_IOT_MQTT_PORT;
 ip.pRootCALocation = AWS_IOT_ROOT_CA_ATS; //AWS_IOT_ROOT_CA
 ip.pDeviceCertLocation = cert;
 ip.pDevicePrivateKeyLocation = priv_key;
 ip.mqttCommandTimeout_ms = 20000;
 ip.tlsHandshakeTimeout_ms = 10000;
 ip.isSSLHostnameVerify = true;
 ip.disconnectHandler = shadow_disconnect_cb;
```

**Comment by gordonwang0** [comment] 2018-12-12 17:36
Hi @tidyjiang8,

I am unsure what the issue is.  Did you modify the platform network layer (i.e. the mbedTLS networks) to get it working on FreeRTOS?

**Comment by tidyjiang8** [comment] 2018-12-14 02:02
Hi @gordonwang0,

Yes, platform network layer has been modified. As I have said above, it can connect to aws iot when I use root CA of "VeriSign". To switch root CA to ATS version, I just modified two parameters: ip.pHostURL & ip.pRootCALocation. What makes me puzzled is that, it still returns error code `SSL_CONNECTION_ERROR`. Anyway, I'll continue to debug this issue later.

**Comment by dcgaws** [comment] 2018-12-14 17:48
@tidyjiang8 can you please provide more information about your embedded device hardware and software/firmware protocol stack? 

Pending that, if you are using Amazon FreeRTOS, along with our wrapper library for mbedTLS, and you have the ability to view serial output from the device, you can enable verbose debug output for TLS. To do that, enable/define MBEDTLS_DEBUG_C in https://github.com/aws/amazon-freertos/blob/master/lib/third_party/mbedtls/include/mbedtls/config.h#L1915. Then do a clean/rebuild and run your app. The traces from mbedTLS should give you more information about what's going wrong.

**Comment by tidyjiang8** [comment] 2018-12-17 04:47
Hi @dcgaws,
I am using MT7697 and its [LinkIt 7697 HDK](https://docs.labs.mediatek.com/resource/mt7687-mt7697/en/get-started-linkit-7697-hdk/gcc-arm-embedded-linkit-7697) while aws-iot-sdk is updated to latest v3.0.1.

```
DEBUG:   iot_tls_connect L#128   . Seeding the random number generator...
DEBUG:   iot_tls_connect L#137   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#153 
===============================
Load Root Ca Succeed
===============================
DEBUG:   iot_tls_connect L#155   . Loading Device Certificate And Key...
DEBUG:   iot_tls_connect L#174 
===============================
Load Devce Cert Succeed
===============================
DEBUG:   iot_tls_connect L#176   . Loading Private Key...
DEBUG:   iot_tls_connect L#199 
===============================
Load Private Key Succeed
===============================
DEBUG:   iot_tls_connect L#202   . Connecting to a2r8jw30a79cph-ats.iot.us-east-1.amazonaws.com:8883...
DEBUG:   iot_tls_connect L#219 
===============================
Connect Server Succeed
===============================
DEBUG:   iot_tls_connect L#226   . Configuring the SSL/TLS Defaults...
DEBUG:   iot_tls_connect L#235 
========================================
Configuring SSL/TLS Defaults Succeed
========================================
DEBUG:   iot_tls_connect L#255   . Setting up mbedtls ssl...
DEBUG:   iot_tls_connect L#265   . SSL state connect : 0 
DEBUG:   iot_tls_connect L#270   . Performing the SSL/TLShandshake...
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:6338 => handshake
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:3279 client state: 0
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2416 => flush output
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2428 <= flush output
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:3279 client state: 1
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2428 <= flush output
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:717 => write client hello
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:755 client hello, max version: [3:3]
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:764 dumping 'client hello, random bytes' (32 bytes)
../..../../../middleware/third_party/mbedtls/library/ssl_cli.c:764 0000:  6b 6e f9 b7 c8 d6 fd 03 11 63 2a d2 e4 2d d5 13  kn.......c*..-..
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:764 0010:  31 4d 47 35 c9 e8 a9 75 ef 14 c8 a6 8b eb 2c 37  1MG5...u......,7
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:817 client hello, session id len.: 0
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:818 dumping 'cient hello, session id' (0 bytes)
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 003d
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 0035
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 003c
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 002f
../../.././../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 000a
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 00af
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 008d
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 00ae
../../../../../middleware/third_party/mbedtls/lirary/ssl_cli.c:885 client hello, add ciphersuite: 008c
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:885 client hello, add ciphersuite: 008b
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:918 client hello, got 11 ciphersuites
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:949 client hello, compress len.: 1
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:951 client hello, compress alg: 0
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:72 client hello, adding server name extension: a2r8jw30a79cph-ats.iot.us-east-1.amazonaws.com
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:178 client hello, adding signature_algorithms extension
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:1023 client hello, total extension length: 71
../../../../../middleware/third_party/mbedtls/library/ssl_tls.:2701 => write record
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2838 output record: msgtype = 22, version = [3:1], msglen = 138
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 dumping 'output record sent to network' (143 bytes)
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0000:  16 03 01 00 8a 01 00 00 86 03 03 6b 6e f9 b7 c8  ...........kn...
../../../../../middleware/third_party/mbedtls/library/sl_tls.c:2841 0010:  d6 fd 03 11 63 2a d2 e4 2d d5 13 31 4d 47 35 c9  ....c*..-..1MG5.
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0020:  e8 a9 75 ef 14 c8 a6 8b eb 2c 37 00 00 16 00 3d  ..u......,7....=
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0030:  00 35 00 3c 00 2f 00 0a 00 af 00 8d 00 ae 00 8c  .5.<./..........
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0040:  00 8b 00 ff 01 0000 47 00 00 00 33 00 31 00 00  .......G...3.1..
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0050:  2e 61 32 72 38 6a 77 33 30 61 37 39 63 70 68 2d  .a2r8jw30a79cph-
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0060:  61 74 73 2e 69 6f 74 2e 75 73 2d 65 61 73 74 2d  ats.iot.us-east-
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0070:  31 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 00  1.mazonaws.com.
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2841 0080:  0d 00 0c 00 0a 06 01 05 01 04 01 03 01 02 01     ...............
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2416 => flush output
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2435 message length: 143, out_left: 143
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2441 ssl->f_send() returned 143 (-0xffffff71)
../.././../../middleware/third_party/mbedtls/library/ssl_tls.c:2460 <= flush output
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2850 <= write record
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:1049 <= write client hello
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:3279 client state: 2
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2416 => flush output
../../../../../middleware/thir_party/mbedtls/library/ssl_tls.c:2428 <= flush output
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:1410 => parse server hello
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:3728 => read record
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2208 => fetch input
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2366 in_left: 0, nb_want: 5
E_SL_MSG_REPORT_IND_ATTR_RESPONSE bFromUart:1, extAddr:0x9d30,u8EndPoint:1,u16ClusterId:0x6,u8AttributeType:0x10,attrId: 0x00, data:1
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2390 in_left: 0, nb_want: 5
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2391 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:2403 <= fetch input
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:3479 dumping 'input record header' (5 bytes)
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:3479 0000:  16 03 03 13 8e                                  .....
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:3488 input record: msgtype = 22, version = [3:3], msglen = 5006
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:3525 bad message length
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:3734 mbedtls_ssl_read_record_layer() returned -29184 (-0x7200)
../../../../../middleware/third_party/mbedtls/library/ssl_cli.c:1416 mbedtls_ssl_read_record() retured -29184 (-0x7200)
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:6349 <= handshake

ERROR: iot_tls_connect L#274  failed  ! mbedtls_ssl_handshake returned -0x7200

../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:6909 => write close notify
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:6925 <= write close notify
../../../../../middleware/third_party/mbedtls/library/ssl_tls.c:7067 => free
../../../../../middlewar/third_party/mbedtls/library/ssl_tls.c:7132 <= free
:../../../../middleware/third_party/mbedtls/library/ssl_tls.c:7132 <= free

```

**Comment by dcgaws** [comment] 2018-12-27 17:17
Hello @tidyjiang8, I have a couple of follow-up questions:

1/ First, what output do you see from the following command?

aws iot describe-endpoint --endpoint-type iot:Data-ATS

(If you haven't setup the AWS CLI environment yet, you can find instructions here, https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html.)

2/ Second, in your device TLS configuration (i.e. in the mbedTLS config), do you have RSA ciphersuites enabled? We still require them for ATS for the time being.

3/ Third, which ATS root certificate are you trusting for server authentication? As a corollary to the above, you need to use the RSA one (i.e. not the ECDSA one).

Thank you.

**Comment by gordonwang0** [comment] 2019-02-14 23:22
Hi @tidyjiang8,

Please let us know if you need any more help with this.  Closing issue.

**Closed by gordonwang0** 2019-02-14 23:22 UTC
Labels: area-mqtt, question, tenet-usability

**Comment by pagiiii** [comment] 2019-09-12 05:46
Hi,
Our embedded device worked well, but when I try to use the new endpoint with '-ats' or '.ats', it reports SSL_CONNECTION_ERROR. I want to know how to resolve that........I also use oneATS root certificates when connecting to an -ats endpoint. I switched my root certificate to one "Amazon Root CAs" (and not the Verisign one) but it doesn't work it still gives SSL_CONNECTION_ERROR .any help will apperciated

By the way, it's very interesting that our device works well with old endpoint (without '-ats')while doesn't work with new endpoint(with '-ats') and our android device is works well with new ats endpoint.

Thanx!!!!!!!!!!!!!!!!
