### ISSUE TITLE
some time fail to connect with aws server even eithernet connected with device

### ISSUE THREAD

**Issue by shileshbabu** [aws/aws-iot-device-sdk-embedded-C#190] opened 2018-06-04 05:20 UTC
Connecting..........................
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to aselfcxbi53y4.iot.ap-south-1.amazonaws.com/8883...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x6800

ERROR: aws_services_initialization L#2029 Error(-4) connecting to HostUrlaselfcxbi53y4.iot.ap-south-1.amazonaws.com:Port8883
connecting fail.................................................. 
Error(-4) connecting to aselfcxbi53y4.iot.ap-south-1.amazonaws.com:8883.....................................

When I am runing my application to initialize & connect with Server,  I am getting SSl hand-shaking error.
My code init Part::

	snprintf(rootCA, PATH_MAX + 1, "%s/%s",    certDirectory, AWS_IOT_ROOT_CA_FILENAME);
	snprintf(clientCRT, PATH_MAX + 1, "%s/%s",  certDirectory, AWS_IOT_CERTIFICATE_FILENAME);
	snprintf(clientKey, PATH_MAX + 1, "%s/%s",  certDirectory, AWS_IOT_PRIVATE_KEY_FILENAME);

	IOT_DEBUG("rootCA %s", rootCA);
	IOT_DEBUG("clientCRT %s", clientCRT);
	IOT_DEBUG("clientKey %s", clientKey);
	data_transfer_ctx->mqttInitParams.enableAutoReconnect = false; // We enable this later below
	data_transfer_ctx->mqttInitParams.pHostURL = HostAddress;
	data_transfer_ctx->mqttInitParams.port = port;
	data_transfer_ctx->mqttInitParams.pRootCALocation = rootCA;
	data_transfer_ctx->mqttInitParams.pDeviceCertLocation = clientCRT;
	data_transfer_ctx->mqttInitParams.pDevicePrivateKeyLocation = clientKey;
	data_transfer_ctx->mqttInitParams.mqttCommandTimeout_ms = 4000;
	data_transfer_ctx->mqttInitParams.tlsHandshakeTimeout_ms = 2000;
	data_transfer_ctx->mqttInitParams.isSSLHostnameVerify = true;
	data_transfer_ctx->mqttInitParams.disconnectHandler = disconnectCallbackHandler;
	data_transfer_ctx->mqttInitParams.disconnectHandlerData = NULL;

		/* reset return flag */
		ret_status = 0;

		rc = aws_iot_mqtt_init(&data_transfer_ctx->client, &data_transfer_ctx->mqttInitParams);
		if(SUCCESS != rc) {
			IOT_ERROR("aws_iot_mqtt_init returned error : %d ", rc);
			printf("aws_iot_mqtt_init returned error : %d....................................... ", rc);
		}
		else{
			data_transfer_ctx->connectParams.keepAliveIntervalInSec = 120;
			data_transfer_ctx->connectParams.isCleanSession = true;
			data_transfer_ctx->connectParams.MQTTVersion = MQTT_3_1_1;
			data_transfer_ctx->connectParams.pClientID = AWS_IOT_MQTT_CLIENT_ID;
			data_transfer_ctx->connectParams.clientIDLen = (uint16_t) strlen(AWS_IOT_MQTT_CLIENT_ID);
			data_transfer_ctx->connectParams.isWillMsgPresent = false;

			IOT_INFO("Connecting..........................");
			rc = aws_iot_mqtt_connect(&data_transfer_ctx->client, &data_transfer_ctx->connectParams);
			if(SUCCESS != rc) {
				IOT_ERROR("Error(%d) connecting to HostUrl%s:Port%d", rc, data_transfer_ctx->mqttInitParams.pHostURL, data_transfer_ctx->mqttInitParams.port);
				printf("connecting fail.................................................. \n");
				printf("Error(%d) connecting to %s:%d.....................................\n", rc, data_transfer_ctx->mqttInitParams.pHostURL, data_transfer_ctx->mqttInitParams.port);
				/* If aws fail to connect, retry after 60 sec. again */
				ret_status = 1;
				sleep(60);
			}
			else{
				/*
				 * Enable Auto Reconnect functionality. Minimum and Maximum time of Exponential backoff are set in aws_iot_config.h
				 *  #AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL
				 *  #AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL
				 */
				rc = aws_iot_mqtt_autoreconnect_set_status(&data_transfer_ctx->client, true);
				if(SUCCESS != rc) {
					IOT_ERROR("Unable to set Auto Reconnect to true - %d", rc);
					printf("Unable to set Auto Reconnect to true - %d...................................................\n", rc);
					//TODO
					//return rc;
				}
			}
		}

Please help me out ???

**Comment by shileshbabu** [comment] 2018-06-08 08:49
Thanks, Gaurav But this time I  am not able to connect IOT device with (GPRS)2G network, But the same configuration working fine with Ethernet, Still is this a certification issue.

**Comment by shileshbabu** [comment] 2018-06-08 09:43
Now what I see, Not able to ping Mubain region Hostname(ping aselfcxbi53y4.iot.ap-south-1.amazonaws.com) but I am able to ping US(ping aselfcxbi53y4.iot.us-east-1.amazonaws.com
), Why this is happening, Is there any issue.


shilesh@shilesh-TravelMate-P249-M:~$ ping aselfcxbi53y4.iot.us-east-1.amazonaws.com
PING dualstack.iotmoonraker-u-elb-1bkszq0bvnbyv-1001897703.us-east-1.elb.amazonaws.com (34.228.102.211) 56(84) bytes of data.
64 bytes from ec2-34-228-102-211.compute-1.amazonaws.com (34.228.102.211): icmp_seq=1 ttl=233 time=197 ms
64 bytes from ec2-34-228-102-211.compute-1.amazonaws.com (34.228.102.211): icmp_seq=2 ttl=233 time=192 ms

64 bytes from ec2-34-228-102-211.compute-1.amazonaws.com (34.228.102.211): icmp_seq=3 ttl=233 time=192 ms
^C
--- dualstack.iotmoonraker-u-elb-1bkszq0bvnbyv-1001897703.us-east-1.elb.amazonaws.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 192.606/194.238/197.484/2.323 ms
shilesh@shilesh-TravelMate-P249-M:~$ ping aselfcxbi53y4.iot.ap-south-1.amazonaws.com
PING dualstack.iotmoonraker-a-elb-3ynv988l077i-924600947.ap-south-1.elb.amazonaws.com (13.126.20.161) 56(84) bytes of data.

**Comment by aggarg** [comment] 2018-06-08 19:16
Ping is right now only allowed in us-east-1 but that should not be a problem.

Are you still not able to connect with GPRS network? If yes, what is the error you are getting?

**Comment by shileshbabu** [comment] 2018-06-11 06:45
Yes Gaurav, With Ethernet it is working fine but 2G airtel GPRS its giving me below error while connecting with server. even i able to ping google.com.


t_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x6800

ERROR: aws_services_initialization L#2029 Error(-4) connecting to HostUrlaselfcxbi53y4.iot.ap-south-1.amazonaws.com:Port8883
connecting fail.................................................. 
Error(-4) connecting to aselfcxbi53y4.iot.ap-south-1.amazonaws.com:8883.....................................


pi@test:~ $ ping google.com
PING google.com (216.58.221.46) 56(84) bytes of data.
64 bytes from del03s07-in-f14.1e100.net (216.58.221.46): icmp_seq=1 ttl=55 time=2280 ms
64 bytes from del03s07-in-f14.1e100.net (216.58.221.46): icmp_seq=3 ttl=55 time=1149 ms
64 bytes from del03s07-in-f14.1e100.net (216.58.221.46): icmp_seq=2 ttl=55 time=2248 ms
64 bytes from del03s07-in-f14.1e100.net (216.58.221.46): icmp_seq=5 ttl=55 time=1590 ms
64 bytes from del03s07-in-f14.1e100.net (216.58.221.46): icmp_seq=4 ttl=55 time=2773 ms
64 bytes from del03s07-in-f14.1e100.net (216.58.221.46): icmp_seq=6 ttl=55 time=951 ms
^C
--- google.com ping statistics ---
7 packets transmitted, 6 received, 14% packet loss, time 6931ms
rtt min/avg/max/mdev = 951.739/1832.358/2773.754/653.371 ms, pipe 3
pi@test:~ $

**Comment by ravibhagavandas** [comment] 2018-06-11 16:13
0x6800 is SSL_TIMEOUT error which still points to a SSL handshake error due to certificate issue. Can you confirm that the certificates are attached to a thing created in ap-south-1 region. Thing name should be same as that defined in Csdk ?
If the certificate is proper, could you also paste the full debug logs from Mbedtls before the handshake error.

**Comment by ManOfSteel1** [comment] 2018-06-12 13:18
Hi @ravibhagavandas. Your comment is very interesting... we are having very similar issues.

We are currently using 2G for connectivity sometimes we seem to miss updates from the devices to the AWS shadow. We communicate every minute when the device is moving. Looking at AWS MQTT logs it appears as though our device is connecting and disconnecting however sometimes it doesn't subscribe or update the shadow. 

Could this be to do with the timeout as you mentioned above?

**Comment by ravibhagavandas** [comment] 2018-06-13 00:43
@ManOfSteel1: Can you paste the relevant logs so that we can investigate the cause ?

**Comment by ManOfSteel1** [comment] 2018-06-13 15:30
Hi @ravibhagavandas as our devices are mobile we don't currently have a efficient way of retrieving MQTT Logs from the devices while they are out on the road. So we can pull off the AWS MQTT logs from the test client... will this help?

**Comment by ManOfSteel1** [comment] 2018-06-13 17:06
ERROR: net_sock_send_tcp_gprs L#261 Send failed.
ERROR: mbedtls_net_send L#133 mbedtls_net_send(): error -1 in net_sock_send() - requestedLen=107
..\..\..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2846: mbedtls_ssl_flush_output() returned -30848 (-0x7880)

..\..\..\Middlewares\Third_Party\mbedTLS\library\ssl_cli.c:2981: mbedtls_ssl_write_record() returned -30848 (-0x7880)

ERROR: iot_tls_connect L#377  failed
  ! mbedtls_ssl_handshake returned -0x7880
FUNC_EXIT:   _aws_iot_mqtt_internal_connect L#404 Return Code : -7 
DEBUG:   AT_RequestSendData L#705 > AT+USOWR=0,107
DEBUG:   AT_RequestSendData L#706 > <tx_data>
osThreadIdFlag_ASENSOR_INT1_ACTIVE signal received
MAIN_MSG_ID_SENSOR_TO_MAIN_MOVEMENT message received (2)
SENSOR_MSG_ID_SENSOR_TO_MAIN_MOVEMENT message sent
DEBUG:   AT_RequestSendData L#717 < AT+USOWR=0,107 @
DEBUG:   AT_RequestSendData L#721 > <tx_data>
osThreadIdFlag_ASENSOR_INT1_ACTIVE signal received
MAIN_MSG_ID_SENSOR_TO_MAIN_MOVEMENT message received (2)
SENSOR_MSG_ID_SENSOR_TO_MAIN_MOVEMENT message sent
DEBUG:   AT_RequestSendData L#735 < 
+USOWR: 0,107

OK

DEBUG:   AT_ExecuteCommand L#659 > AT+USOCL=0
DEBUG:   AT_ExecuteCommand L#670 < AT+USOCL=0 OK

FUNC_ENTRY:   aws_iot_mqtt_set_client_state L#110 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#63 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#68 Return Code : 2 
FUNC_EXIT:   aws_iot_mqtt_set_client_state L#135 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_connect L#490 Return Code : -7 
ERROR: aws_subscribe_publish_sensor_values L#353 FAILED: aws_iot_mqtt_internal_connect returned -0x7

ERROR: aws_subscribe_publish_sensor_values L#359 Error(-7) connecting to a3j6p2emr9wa49.iot.eu-west-2.amazonaws.com:443
FUNC_ENTRY:   aws_iot_mqtt_disconnect L#553 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#63 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#68 Return Code : 11 
FUNC_ENTRY:   aws_iot_mqtt_is_client_connected L#292 
FUNC_EXIT:   aws_iot_mqtt_is_client_connected L#326 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_disconnect L#562 Return Code : -13 

MQTT Connection terminated -13
ERROR: aws_subscribe_publish_sensor_values L#611 AWS p*** GPRS deinit successfully ***
Heap Max allocation 0x7704 (30468), current allocation 0x0 (0), Stack max size 0xfffffff0 (-16)
Cached logs 2
Cached messages 2 

Network connection powered down

**Comment by ravibhagavandas** [comment] 2018-06-16 01:00
**ERROR: iot_tls_connect L#377 failed
! mbedtls_ssl_handshake returned -0x7880**
0x7880 is MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY which seems server closed the connection while writing to the socket. Could you also send the logs from the startup to know which part of the handshake failed ? 
Also which version of mbedtls are you using ? Because it doesn't match with library in my setup.

**Comment by shileshbabu** [comment] 2018-06-18 07:41
Sorry for delay reply, Please see below logs.
With the same configuration, its working fine on Eithernet, but on 2G GPRS connection it's giving below error. is this a 2g network issue?  

Version--->mbedtls-2.9.0
<<<<<<<<<<<<<<<<<<<<<-----AWS__logs_start_from_here--->>>>>>>>>>>>>

AWS IoT SDK Version 3.0.0-

DEBUG:   aws_services_initialization L#1992 rootCA /home/pi/certs/root-CA.crt
DEBUG:   aws_services_initialization L#1993 clientCRT /home/pi/certs/IOT_NODEX_TESTING.cert.pem
DEBUG:   aws_services_initialization L#1994 clientKey /home/pi/certs/IOT_NODEX_TESTING.private.key
Connecting..........................
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to aselfcxbi53y4.iot.ap-south-1.amazonaws.com/8883...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x6800

ERROR: aws_services_initialization L#2029 Error(-4) connecting to HostUrlaselfcxbi53y4.iot.ap-south-1.amazonaws.com:Port8883
connecting fail.................................................. 
Error(-4) connecting to aselfcxbi53y4.iot.ap-south-1.amazonaws.com:8883.....................................

**Comment by ravibhagavandas** [comment] 2018-06-18 16:56
Error code -0x6800 is for SSL handshake Timeout.
From MbedTLS code:
`#define MBEDTLS_ERR_SSL_TIMEOUT                           -0x6800  /**< The operation timed out. */ >`

But the tcp connection has succeeded, which means the broker is reachable:
**DEBUG: iot_tls_connect L#161 . Connecting to aselfcxbi53y4.iot.ap-south-1.amazonaws.com/8883...
DEBUG: iot_tls_connect L#180 ok**

Are there any firewall rules in your network, which prevents the connection from proceeding further?

Also you could try increasing the timeout value for ssl handshake defined in MQTT init params. For example, ssl handshake timeout for publish subscribe example is defined here:
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c#L169 

If this doesn't work, you can enable mbedTLS debug logs and inspect further at what step handshake timedout. Debug logs can be enabled by defining MBEDTLS_DEBUG_C in mbedTLS's `config.h` and adding a call to `mbedtls_debug_set_threshold(4)` before connecting the AWS_IoT_Client.

**Comment by ManOfSteel1** [comment] 2018-06-21 14:44
Hi @ravibhagavandas 

Sorry for the delay, here is the an example of the 0x7880 error: 

`
*** Initialise network connection ***
Initializing the GPRS module
AppGPS: GPS_STATE_POWERED_ACQUIRE
AppGPS: GPS_STATE_POWERED_ACQUIRED
osThreadIdFlag_SENSORS_READ signal received
MAIN_MSG_ID_GPS_TO_MAIN_UPDATE message received
GPS_MSG_ID_GPS_TO_MAIN_UPDATE message sent
AppGPS: GPS_STATE_POWERED_IDLE
Temperature Read Complete: 318
MAIN_MSG_ID_SENSORS_TO_MAIN_UPDATE message received
AppMain: MAIN_STATE_INACTIVE_ACQUIRING_GPS
AppMain: MAIN_STATE_ACTIVE_ACQUIRING_ALARM
SENSOR_MSG_ID_SENSOR_TO_MAIN_UPDATE message sent 
Module initialized successfully: SARA-G340-02S-00
Provision AP network connection
Connecting to network

Connecting to AP: internet4gd.gdsp
GPRSState: UB_GPRS_STATE_INITIALISED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
AppGPS: GPS_STATE_POWERED_ACQUIRE
AppGPS: GPS_STATE_POWERED_ACQUIRED
MAIN_MSG_ID_GPS_TO_MAIN_UPDATE message received
GPS_MSG_ID_GPS_TO_MAIN_UPDATE message sent
AppGPS: GPS_STATE_POWERED_IDLE
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_READY
GPRSState: UB_GPRS_STATE_REGISTERED
Network Operator: EE
GPRSState: UB_GPRS_STATE_REGISTERED
GPRSState: UB_GPRS_STATE_CONNECTING
GPRSState: UB_GPRS_STATE_CONNECTED
Connected to AP:
Retrieving the IP address
IP address: 10.57.54.13
GPRS Connecting

Subscribing to AWS IoT services
Cached logs 1
AWS IoT SDK Version 3.0.1-001
FUNC_ENTRY:   aws_iot_mqtt_init L#210 
FUNC_ENTRY:   aws_iot_mqtt_set_connect_params L#139 
FUNC_EXIT:   aws_iot_mqtt_set_connect_params L#169 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_init L#281 Return Code : 0 
MQTT connection in progress
FUNC_ENTRY:   aws_iot_mqtt_connect L#461 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#63 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#68 Return Code : 1 
FUNC_ENTRY:   aws_iot_mqtt_set_client_state L#110 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#63 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#68 Return Code : 1 
FUNC_EXIT:   aws_iot_mqtt_set_client_state L#135 Return Code : 0 
FUNC_ENTRY:   _aws_iot_mqtt_internal_connect L#391 
FUNC_ENTRY:   aws_iot_mqtt_set_connect_params L#139 
FUNC_EXIT:   aws_iot_mqtt_set_connect_params L#169 Return Code : 0 
ERROR: net_sock_send_tcp_gprs L#261 Send failed.
ERROR: mbedtls_net_send L#133 mbedtls_net_send(): error -1 in net_sock_send() - requestedLen=182
..\..\..\Middlewares\Third_Party\mbedTLS\library\ssl_tls.c:2846: mbedtls_ssl_flush_output() returned -30848 (-0x7880)

..\..\..\Middlewares\Third_Party\mbedTLS\library\ssl_cli.c:1045: mbedtls_ssl_write_record() returned -30848 (-0x7880)

ERROR: iot_tls_connect L#377  failed
  ! mbedtls_ssl_handshake returned -0x7880
FUNC_EXIT:   _aws_iot_mqtt_internal_connect L#404 Return Code : -7 
FUNC_ENTRY:   aws_iot_mqtt_set_client_state L#110 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#63 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#68 Return Code : 2 
FUNC_EXIT:   aws_iot_mqtt_set_client_state L#135 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_connect L#490 Return Code : -7 
ERROR: aws_subscribe_publish_sensor_values L#353 FAILED: aws_iot_mqtt_internal_connect returned -0x7

ERROR: aws_subscribe_publish_sensor_values L#359 Error(-7) connecting to a3j6p2emr9wa49.iot.eu-west-2.amazonaws.com:443
FUNC_ENTRY:   aws_iot_mqtt_disconnect L#553 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#63 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#68 Return Code : 11 
FUNC_ENTRY:   aws_iot_mqtt_is_client_connected L#292 
FUNC_EXIT:   aws_iot_mqtt_is_client_connected L#326 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_disconnect L#562 Return Code : -13 

MQTT Connection terminated -13
ERROR: aws_subscribe_publish_sensor_values L#611 AWS publication error occured (-13)

*** Disconnect network connection ***`

**Comment by ravibhagavandas** [comment] 2018-06-25 21:37
Seems the send failure comes from the underlying TCP socket due to a network connectivity issue:

ERROR: net_sock_send_tcp_gprs L#261 Send failed.

 Is your network stable ?
If not, I  would suggest you to add more retries with exponential backoff to `aws_iot_mqtt_connect ` from application level.

**Comment by lt72** [comment] 2018-07-09 19:49
Hi @ManOfSteel1, did you have a chance to try @ravibhagavandas 's suggestion?

**Comment by gordonwang0** [comment] 2018-07-25 20:59
Hello everyone,

It looks like discussion in this thread has run its course.  I will close the issue.  Please let us know if you need any more help.

**Closed by gordonwang0** 2018-07-25 20:59 UTC
Labels: area-mqtt, question, tenet-usability
